orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
version: 2.1
executors:
  docker-riotbuild:
    docker:
      - image: riot/riotbuild
    resource_class: large
jobs:
  build:
    executor: docker-riotbuild
    steps:
      - checkout
      - run:
          name: Checkout git submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: Install build-wrapper
          command: |
            wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
            unzip build-wrapper-linux-x86.zip
            cp build-wrapper-linux-x86/libinterceptor-x86_64.so build-wrapper-linux-x86/libinterceptor-haswell.so
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build the application
          command: |
            ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bin make
      - sonarcloud/scan
      - store_artifacts:
          path: bin
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - sonarcloud.io
          filters:
            branches:
              ignore:
                - gh-pages
