version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  docker-riotbuild:
    docker:
      - image: riot/riotbuild
    resource_class: medium

commands:
  checkout-with-submodules:
    description: "Checkout code and restore/update submodules with caching"
    steps:
      - checkout
      - restore_cache:
          keys:
            - submodules-v1-{{ checksum ".gitmodules" }}
            - submodules-v1-
      - run:
          name: Checkout git submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - save_cache:
          key: submodules-v1-{{ checksum ".gitmodules" }}
          paths:
            - .git/modules

jobs:
  build-and-analyze:
    executor: docker-riotbuild
    steps:
      - checkout-with-submodules
      - restore_cache:
          keys:
            - sonar-wrapper-v1
      - run:
          name: Install the SonarCloud scanner wrapper
          command: |
            if [ ! -d "build-wrapper-linux-x86" ]; then
              wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
              unzip build-wrapper-linux-x86.zip
              cp build-wrapper-linux-x86/libinterceptor-x86_64.so build-wrapper-linux-x86/libinterceptor-haswell.so
            fi
      - save_cache:
          key: sonar-wrapper-v1
          paths:
            - build-wrapper-linux-x86
      - run:
          name: Build the application with build-wrapper
          command: |
            ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bin make
      - sonarcloud/scan
      - store_artifacts:
          path: bin

  build:
    executor: docker-riotbuild
    parameters:
      board:
        type: string
    steps:
      - checkout-with-submodules
      - run:
          name: Build for << parameters.board >>
          command: |
            make BOARD=<< parameters.board >>
      - store_artifacts:
          path: bin
          destination: << parameters.board >>

workflows:
  commit-build:
    jobs:
      - build-and-analyze:
          context:
            - sonarcloud.io
          filters:
            branches:
              ignore:
                - gh-pages
      - build:
          name: build-arduino-leonardo
          board: arduino-leonardo
          filters:
            branches:
              ignore:
                - gh-pages

  weekly-build:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-analyze:
          context:
            - sonarcloud.io
      - build:
          name: build-arduino-leonardo
          board: arduino-leonardo
